#:import dp kivy.metrics.dp
<MatchRegisterScreen>:
    MDBoxLayout:
        orientation: 'vertical'
        spacing: dp(10)
        padding: dp(20)

        MDLabel:
            text: '[試合データ登録画面]'
            halign: 'center'
            font_name: app.font_name

        MDRaisedButton:
            text: '戻る'
            font_name: app.font_name
            on_release: root.change_screen('menu')
